local map = vim.keymap.set

map("n", "<leader>w", "<cmd>w<cr>", { desc = "Save file" })
map("n", "<leader>q", "<cmd>q<cr>", { desc = "Quit window" })
map("n", "<leader>h", "<C-w>h", { desc = "Go left window" })
map("n", "<leader>j", "<C-w>j", { desc = "Go down window" })
map("n", "<leader>k", "<C-w>k", { desc = "Go up window" })
map("n", "<leader>l", "<C-w>l", { desc = "Go right window" })
map("n", "<leader>e", "<cmd>Neotree toggle<cr>", { desc = "Toggle project tree" })
map("n", "<leader>r", "<cmd>RunFile<cr>", { desc = "Run current file" })
map("n", "<S-l>", "<cmd>BufferLineCycleNext<cr>", { desc = "Next tab" })
map("n", "<S-h>", "<cmd>BufferLineCyclePrev<cr>", { desc = "Prev tab" })
map("n", "<leader>bd", "<cmd>bdelete<cr>", { desc = "Close current tab" })
map("n", "<leader>bp", "<cmd>BufferLineTogglePin<cr>", { desc = "Pin tab" })
map("n", "<leader>ff", "<cmd>Telescope find_files<cr>", { desc = "Find files" })
map("n", "<leader>fg", "<cmd>Telescope live_grep<cr>", { desc = "Search in project" })
map("n", "<leader>fb", "<cmd>Telescope buffers<cr>", { desc = "Find tab/buffer" })
map("n", "<leader>sr", "<cmd>SessionRestore<cr>", { desc = "Restore session" })
map("n", "<leader>ss", "<cmd>SessionSave<cr>", { desc = "Save session" })
map("n", "<leader>tt", "<cmd>ToggleTerm<cr>", { desc = "Toggle run panel" })

map("n", "<F5>", function()
  require("dap").continue()
end, { desc = "Debug continue/start" })
map("n", "<F10>", function()
  require("dap").step_over()
end, { desc = "Debug step over" })
map("n", "<F11>", function()
  require("dap").step_into()
end, { desc = "Debug step into" })
map("n", "<F12>", function()
  require("dap").step_out()
end, { desc = "Debug step out" })
map("n", "<leader>db", function()
  require("dap").toggle_breakpoint()
end, { desc = "Debug breakpoint" })
map("n", "<leader>du", function()
  require("dapui").toggle()
end, { desc = "Debug UI toggle" })
