[libdefaults]
    default_realm = EXAMPLE.COM
    dns_lookup_realm = false
    dns_lookup_kdc = false
    rdns = false
    forwardable = true
    udp_preference_limit = 1
    default_ccache_name = FILE:/tmp/krb5cc_%{uid}
    ticket_lifetime = 10h
    renew_lifetime = 7d
    kdc_timesync = 1
    max_retries = 3

[realms]
    EXAMPLE.COM = {
        kdc = dc01.example.com
        kdc = dc02.example.com
        admin_server = dc01.example.com
        default_domain = example.com
    }

[domain_realm]
    .example.com = EXAMPLE.COM
    example.com = EXAMPLE.COM
