apiVersion: v1
kind: Secret
metadata:
  name: kerberos-sso-secrets
  namespace: kerberos-sso
type: Opaque
data:
  # base64 of service.keytab
  service.keytab: "REPLACE_WITH_BASE64_KEYTAB"
  # base64 of krb5.conf
  krb5.conf: "REPLACE_WITH_BASE64_KRB5_CONF"
